### ISSUE TITLE
Рефракторинг

### ISSUE THREAD

**Issue by maxim-kozlov** [YoungMeatBoy/summerPractise#1]
https://github.com/YoungMeatBoy/summerPractise/blob/609073ee0d9da8f744358bd91eccb28e98f9e87e/companies.py#L101

info можно оставить, но что насчёт переопределения __str__ ?

https://github.com/YoungMeatBoy/summerPractise/blob/a736b69280d8b1ddd7e93691dc0ecfb45e88c36c/companies.py#L25
Чисто логически компания, может уже иметь акции, у тебя это не учтено

**Comment by YoungMeatBoy** [comment]
а зачем?

**Comment by YoungMeatBoy** [comment]
общее количество акций у компании будем выбирать рандомом

**Comment by maxim-kozlov** [comment]
why not?
```python 3
def __str__(self):
    return """
info about company
"""
```

**Comment by YoungMeatBoy** [comment]
ну можно и так
только суть именно в возвращении словаря
